import Head from "next/head";
import { useRef, useState } from "react";

function Home() {
    const [hasPassword, setHasPassword] = useState(false);
    const passwordRef = useRef<HTMLInputElement>(null);
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex h-full w-full flex-col items-center justify-center">
                <div className="min-h-64 flex flex-col items-center italic">
                    <h1 className="text-5xl">Rank Thyme</h1>
                    <button
                        type="submit"
                        className="my-8 h-9 w-28 rounded-md border-2 border-white bg-blue-300"
                    >
                        Create
                    </button>
                    <label className="flex flex-row items-center gap-1">
                        <input
                            type="checkbox"
                            checked={hasPassword}
                            onChange={() => {
                                setHasPassword(!hasPassword);
                                passwordRef.current?.focus();
                            }}
                        />
                        Set a password?
                    </label>
                    <input
                        ref={passwordRef}
                        type="password"
                        className={`my-1 h-6 w-56 rounded-md border-2 border-white bg-white p-1 ${
                            hasPassword ? "" : "hidden"
                        }`}
                    />
                </div>
            </div>
        </>
    );
}

export default Home;
