import Head from "next/head";
import type { ReactNode } from "react";

interface Props {
    children: ReactNode;
}

export function PageContainer({ children }: Props) {
    return (
        <>
            <Head>
                <title>Rank Thyme!</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex h-full w-full flex-col items-center">
                <h1 className="my-12 text-5xl">Rank Thyme</h1>
                {children}
            </div>
        </>
    );
}
