import Head from "next/head";
import Link from "next/link";
import type { ReactNode } from "react";

interface Props {
    children: ReactNode;
}

export function PageContainer({ children }: Props) {
    return (
        <>
            <Head>
                <title>Rank Thyme!</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <svg width="0" height="0">
                <filter id="kill">
                    <feColorMatrix
                        type="matrix"
                        result="red_"
                        values="
                            4 0 0 0 0
                            0 0 0 0 0
                            0 0 0 0 0
                            0 0 0 1 0
                        "
                    />
                    <feOffset in="red_" dx="1" dy="0" result="red" />
                    <feColorMatrix
                        type="matrix"
                        in="SourceGraphic"
                        result="blue_"
                        values="
                            0 0 0 0 0
                            0 3 0 0 0
                            0 0 10 0 0
                            0 0 0 1 0
                        "
                    />
                    <feOffset in="blue_" dx="-2" dy="0" result="blue" />
                    <feBlend mode="screen" in="red" in2="blue" />
                </filter>
                <filter id="noiseFilter">
                    <feTurbulence
                        type="fractalNoise"
                        baseFrequency="0.65"
                        numOctaves="3"
                        stitchTiles="stitch"
                    />
                </filter>
            </svg>

            <div className="flex h-full w-full flex-col items-center">
                <div
                    className="pointer-events-none absolute h-full w-full"
                    style={{ WebkitFilter: "url(#noiseFilter)" }}
                />
                <Link href="/">
                    <h1
                        className="beepis my-12 text-5xl text-purple-300"
                        style={{
                            WebkitFilter: "url(#kill)",
                        }}
                    >
                        Rank Thyme
                        <div className="beepis" />
                    </h1>
                </Link>
                {children}
            </div>
        </>
    );
}
